function [y,iters] = BP_iterate_matlab(x,H,l)

decoder = comm.LDPCDecoder...
    ('ParityCheckMatrix',H,'OutputValue','Whole codeword',...
    'DecisionMethod','Hard decision',...
    'IterationTerminationCondition','Parity check satisfied',...
    'MaximumIterationCount',l,...
    'NumIterationsOutputPort',true);
[y,iters] = step(decoder,x');

end

