function y = cdf_func(x,u,mu_ret,sigma_ret,lambda)

positive = (1/4)*exp((-x+u+mu_ret)/lambda)*(exp((sigma_ret^2)/(2*lambda^2)) ...
    - exp((-u-mu_ret)/lambda)*erfc((-u-mu_ret)/lambda*sqrt(2)) ...
    - exp((sigma_ret^2)/(2*lambda^2))*erf(((-u-mu_ret)/(sigma_ret*sqrt(2))) ...
    - ((sigma_ret*sqrt(2))/(2*lambda))));

% negative = (1/4)*exp((x-u-mu_ret)/lambda)*(-exp((u+mu_ret)/lambda)...
%     *erfc((-u-mu_ret)/(sigma_ret*sqrt(2)))-exp((sigma_ret^2)/(2*lambda^2))...
%     *erf(((-u-mu_ret)/(sigma_ret*sqrt(2)))+((sigma_ret*sqrt(2))/(2*lambda))) ...
%     - exp((sigma_ret^2)/(2*lambda^2)));

negative = (1/4)*exp((x-u-mu_ret)/lambda)*(exp((sigma_ret^2)/(2*lambda^2)) ...
    - exp((u+mu_ret)/lambda)*erfc((u+mu_ret)/lambda*sqrt(2)) ...
    - exp((sigma_ret^2)/(2*lambda^2))*erf(((u+mu_ret)/(sigma_ret*sqrt(2))) ...
    - ((sigma_ret*sqrt(2))/(2*lambda))));

y = positive + negative;


end